### ISSUE TITLE
Short name support?

### ISSUE THREAD

**Issue by milesj** [dematerializer/unicode-emoji-data#2]
First off, awesome library. I was looking to replace EmojiOne with this library in my Interweave project (https://github.com/milesj/interweave), but it does not support short names, like `:cat:`, `:thumbsup:`, etc.

I know short names are not a true standard, more of a community one, but is that something this library would support?

**Comment by dematerializer** [comment]
Thanks! Also for your interest in using unicode-emoji-data in a real world application!

I created this module with the Unix Philosophy in mind, so it does only one thing well, which is providing the original emoji data from Unicode as a single JSON structure by being as standard-compliant as possible.

So I won't add any additional content like short names.

The second part of the underlying philosophy is that a module should easily compose with other modules. This is also true for unicode-emoji-data: as the contained emoji data entries can be accessed by their standard code point, you as the user of this library could easily create a mapping to data provided by other libraries if they also let you access their entries by standard code points.

Therefore I see no problem using this library in conjunction with short name data provided by EmojiOne.

As I see in your source code, you are only interested in the hex codes and short names from EmojiOne. I would not recommend using unicode-emoji-data in your interweave project unless you have good reason to use the emoji properties it provides in addition to what you already get from EmojiOne.

**Comment by milesj** [comment]
Sounds good. Thanks for the awesome feedback and response!
